import java.sql.*; //using this for the connect, not sure which one would have been correct
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.sql.DriverManager;
import com.mysql.cj.jdbc.Driver;

public class MySQLAdsDao implements Ads {
    private Connection connection;
    private Config config = new Config();


    public MySQLAdsDao(Config config) {
        try {
            DriverManager.registerDriver(new Driver());
//            new Driver();
            this.connection = DriverManager.getConnection(
                    config.getUrl(),
                    config.getUser(),
                    config.getPassword()
            );

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    @Override
    public List<Ad> all() {
        String selectQuery = "SELECT * FROM ads";
        Statement statement = null;
        ResultSet resultSet = null;
        List<Ad> ads = new ArrayList<>();

        try{
            statement = connection.createStatement();
            resultSet = statement.executeQuery(selectQuery);
            while (resultSet.next()) {
                Ad ad = new Ad(resultSet.getLong("id"), resultSet.getLong("user_id"), resultSet.getString("title"), resultSet.getString("description"));

                ads.add(ad);
            }
        } catch (SQLException throwables){
            throwables.printStackTrace();
        }
        return ads;
    }

    @Override
    public Long insert(Ad ad) {
        Long lastInsertedId = 0L;
        try {
            Statement statement = connection.createStatement();
            ResultSet resultSet = null;
//            String insertQuery = "INSERT INTO ads (user_id, title, description) VALUES (ad.getUserId(), ad.getTitle(), ad.getDescription())"; //this one doesn't work, but the one below it does, I think it has to do with the data type. Maybe there's another way to cast to int or cast to string here.
            String insertQuery = String.format("INSERT INTO ads (user_id, title, description) VALUES (%d, '%s', '%s')",
                    ad.getUserId(), ad.getTitle(), ad.getDescription());

            statement.executeUpdate(insertQuery, Statement.RETURN_GENERATED_KEYS); //use executeUpdate, not executeQuery here
            resultSet = statement.getGeneratedKeys(); //the getGeneratedKeys method will give us a result set object that holds any ids that were generated by the database
            resultSet.next();  //you call the next method to advance through the results
            lastInsertedId = resultSet.getLong(1);  //we use getLong and pass in a 1 to indicate that we want the first result in the result set
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return lastInsertedId;  //the return value of executeUpdate is the number of rows affected
    }
}
